'use strict';

import {
  fetchDefaultUserRole,
  isUsernameEmailInUse,
  createNewUser,
  getUserInfo,
  registerEmailVerification,
  fetchUserMetaInfo,
  verifyUserEmail,
  getUserInfoByUsernameOrPassword,
  getUserPasskey,
  storeUserToken,
  getUserDtl,
  logoutUser,
} from './user.db.js';

import {
  isRoleAvailable,
  getDefaultRole,
  deactivateRole,
  registerNewRole,
  getUserRoleById,
  getUserRoles,
  updateUserRoleById,
  deleteUserRoleById,
  isScopeAvailable,
  registerNewScope,
  getUserScopeById,
  getUserScopes,
  updateUserScopeById,
  deleteUserScopeById,
  unassignedScopesByRoleId,
  assignedScopesByRoleId,
  getMultipleScopesByIds,
  assignScopesToRole,
  unassignScopesToRole,
  isServiceAvailable,
  registerNewService,
  getServiceById,
  getServiceConfig,
  isRouteAvailable,
  registerNewRoute,
  getRouteById,
  getRouteConfig,
} from './system.db.js';

export {
  fetchDefaultUserRole,
  isUsernameEmailInUse,
  createNewUser,
  getUserInfo,
  registerEmailVerification,
  fetchUserMetaInfo,
  verifyUserEmail,
  getUserInfoByUsernameOrPassword,
  getUserPasskey,
  storeUserToken,
  getUserDtl,
  logoutUser,
  isRoleAvailable,
  getDefaultRole,
  deactivateRole,
  registerNewRole,
  getUserRoleById,
  getUserRoles,
  updateUserRoleById,
  deleteUserRoleById,
  isScopeAvailable,
  registerNewScope,
  getUserScopeById,
  getUserScopes,
  updateUserScopeById,
  deleteUserScopeById,
  unassignedScopesByRoleId,
  assignedScopesByRoleId,
  getMultipleScopesByIds,
  assignScopesToRole,
  unassignScopesToRole,
  isServiceAvailable,
  registerNewService,
  getServiceById,
  getServiceConfig,
  isRouteAvailable,
  registerNewRoute,
  getRouteById,
  getRouteConfig,
};
