'use strict';

import {
    isSettingAvailable,
    registerNewSetting,
    getAllSettings,
    getSettingInfoById,
    getSystemUserSettingInfo,
    getUserAssignableSettings,
    isRouteAvailable,
    registerNewRoute,
    isUserRoleAvailable,
    isUserRoleByIdAvailable,
    isDefaultUserRoleAvailable,
    registerNewUserRole,
    getAllUserRole,
    getUserRoleById,
    updateUserRoleById,
    deleteUserRoleById,
    isScopeAvailable,
    registerNewScope,
    getAllUserScope,
    getUserScopeById,
    updateUserScopeById,
    deleteUserScopeById,
    getAllAppRoute,
    getAppRouteById,
    updateAppRouteById,
    deleteAppRouteById,
    createUserSettings
} from './settings.db.js';
import {
    isUserByUsernameOrEmailAvailable,
    createNewUser,
    assignUserRole,
    isUserByIdAvailable,
    getUserFullDetails,
    validateUser
} from './users.db.js';

export default {
    isSettingAvailable,
    registerNewSetting,
    getAllSettings,
    getSettingInfoById,
    getSystemUserSettingInfo,
    getUserAssignableSettings,
    isRouteAvailable,
    registerNewRoute,
    isUserRoleAvailable,
    isUserRoleByIdAvailable,
    isDefaultUserRoleAvailable,
    registerNewUserRole,
    getAllUserRole,
    getUserRoleById,
    updateUserRoleById,
    deleteUserRoleById,
    isScopeAvailable,
    registerNewScope,
    getAllUserScope,
    getUserScopeById,
    updateUserScopeById,
    deleteUserScopeById,
    getAllAppRoute,
    getAppRouteById,
    updateAppRouteById,
    deleteAppRouteById,
    isUserByUsernameOrEmailAvailable,
    createNewUser,
    createUserSettings,
    assignUserRole,
    isUserByIdAvailable,
    getUserFullDetails,
    validateUser
};
